pipeline {
    agent any
    
    environment {
        registry = 'http://127.0.0.1:8123/repository/docker-reg/'
        git_credential = '371f477d-c68d-4d2b-8c6a-90a424057e36'
        nexus_credential = '15cf88cf-a201-4b67-b155-0fd885cadd8b'
        imagename = 'nodeweb'
    }

    stages {
        stage('Pull code from git') {
            steps {
                //git config
                git credentialsId: git_credential, url: 'https://github.com/grhovo/docker-react.git'
                
            }
        }
        stage('Buld docker image'){
            steps {
                script 
                {
                    dockerImage = docker.build imagename
                }
            }
        }
        stage('Push image to nexus repo'){
            steps {
                script
                {
                    docker.withRegistry( registry, nexus_credential ) {
                    dockerImage.push("$BUILD_NUMBER")
                    dockerImage.push('latest')
                    }
                }
        }
    }
    }
}
